# Generated by Django 3.0.6 on 2020-05-25 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='Имя', max_length=200)),
                ('user_jobtitle', models.CharField(default='Сотрудник', max_length=200)),
                ('user_image', models.ImageField(blank=True, upload_to='user/%Y/%m/%d')),
                ('diplom_name', models.CharField(default='Имя диплома', max_length=200)),
                ('diplom_descr', models.CharField(default='Описание диплома', max_length=200)),
                ('diplom_image', models.ImageField(blank=True, upload_to='diplom/%Y/%m/%d')),
                ('org_name', models.CharField(default='имя организации', max_length=200)),
                ('org_url', models.CharField(default='https://www.susu.ru/', max_length=200)),
                ('org_email', models.CharField(default='info@susu.ru', max_length=200)),
                ('org_image', models.ImageField(blank=True, upload_to='org/%Y/%m/%d')),
                ('json_file', models.FileField(blank=True, upload_to='json/%Y/%m/%d')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
