# Generated by Django 3.0.6 on 2020-05-26 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chdi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='diplom_image',
        ),
        migrations.RemoveField(
            model_name='template',
            name='json_file',
        ),
        migrations.RemoveField(
            model_name='template',
            name='org_image',
        ),
        migrations.RemoveField(
            model_name='template',
            name='user_image',
        ),
        migrations.AddField(
            model_name='template',
            name='json_data',
            field=models.CharField(default='json data', max_length=1500),
        ),
    ]
