# Generated by Django 3.0.6 on 2020-05-29 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chdi', '0006_auto_20200530_0127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
