# Generated by Django 3.0.6 on 2020-05-29 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chdi', '0007_auto_20200530_0128'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
