# Generated by Django 3.0.6 on 2020-05-29 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chdi', '0009_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='patronymic',
            field=models.CharField(default='Ивановна', max_length=200),
        ),
    ]
